package com.deemsys.project.entity;

// Generated 31 Jan, 2018 6:26:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activity", catalog = "injuryreportsdb")
public class Activity implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer status;
	private Set<ActivityLogs> activityLogses = new HashSet<ActivityLogs>(0);

	public Activity() {
	}

	public Activity(String name, Integer status,
			Set<ActivityLogs> activityLogses) {
		this.name = name;
		this.status = status;
		this.activityLogses = activityLogses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activity")
	public Set<ActivityLogs> getActivityLogses() {
		return this.activityLogses;
	}

	public void setActivityLogses(Set<ActivityLogs> activityLogses) {
		this.activityLogses = activityLogses;
	}

}
