package com.deemsys.project.entity;

// Generated 31 Jan, 2018 6:26:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActivityLogs generated by hbm2java
 */
@Entity
@Table(name = "activity_logs", catalog = "injuryreportsdb")
public class ActivityLogs implements java.io.Serializable {

	private ActivityLogsId id;
	private IpAccessList ipAccessList;
	private Users usersByLoginId;
	private Activity activity;
	private Users usersByPrimaryId;

	public ActivityLogs() {
	}

	public ActivityLogs(ActivityLogsId id) {
		this.id = id;
	}

	public ActivityLogs(ActivityLogsId id, IpAccessList ipAccessList,
			Users usersByLoginId, Activity activity, Users usersByPrimaryId) {
		this.id = id;
		this.ipAccessList = ipAccessList;
		this.usersByLoginId = usersByLoginId;
		this.activity = activity;
		this.usersByPrimaryId = usersByPrimaryId;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sessionId", column = @Column(name = "session_id", length = 32)),
			@AttributeOverride(name = "loginId", column = @Column(name = "login_id")),
			@AttributeOverride(name = "primaryId", column = @Column(name = "primary_id")),
			@AttributeOverride(name = "activityId", column = @Column(name = "activity_id")),
			@AttributeOverride(name = "ipAddress", column = @Column(name = "ip_address")),
			@AttributeOverride(name = "accessDate", column = @Column(name = "access_date", length = 10)),
			@AttributeOverride(name = "accessInTime", column = @Column(name = "access_in_time", length = 45)),
			@AttributeOverride(name = "accessOutTime", column = @Column(name = "access_out_time", length = 45)),
			@AttributeOverride(name = "description", column = @Column(name = "description", length = 60)),
			@AttributeOverride(name = "status", column = @Column(name = "status")) })
	public ActivityLogsId getId() {
		return this.id;
	}

	public void setId(ActivityLogsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "primary_id", referencedColumnName = "primary_login_id", insertable = false, updatable = false),
			@JoinColumn(name = "ip_address", referencedColumnName = "ip_address", insertable = false, updatable = false) })
	public IpAccessList getIpAccessList() {
		return this.ipAccessList;
	}

	public void setIpAccessList(IpAccessList ipAccessList) {
		this.ipAccessList = ipAccessList;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login_id", insertable = false, updatable = false)
	public Users getUsersByLoginId() {
		return this.usersByLoginId;
	}

	public void setUsersByLoginId(Users usersByLoginId) {
		this.usersByLoginId = usersByLoginId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "activity_id", insertable = false, updatable = false)
	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "primary_id", insertable = false, updatable = false)
	public Users getUsersByPrimaryId() {
		return this.usersByPrimaryId;
	}

	public void setUsersByPrimaryId(Users usersByPrimaryId) {
		this.usersByPrimaryId = usersByPrimaryId;
	}

}
