package com.deemsys.project.entity;

// Generated 31 Jan, 2018 6:26:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActivityLogsId generated by hbm2java
 */
@Embeddable
public class ActivityLogsId implements java.io.Serializable {

	private String sessionId;
	private Integer loginId;
	private Integer primaryId;
	private Integer activityId;
	private String ipAddress;
	private Date accessDate;
	private String accessInTime;
	private String accessOutTime;
	private Integer recordsCount;
	private String description;
	private Integer status;

	public ActivityLogsId() {
	}

	public ActivityLogsId(String sessionId, Integer loginId, Integer primaryId,
			Integer activityId, String ipAddress, Date accessDate,
			String accessInTime, String accessOutTime, Integer recordsCount, 
			String description, Integer status) {
		this.sessionId = sessionId;
		this.loginId = loginId;
		this.primaryId = primaryId;
		this.activityId = activityId;
		this.ipAddress = ipAddress;
		this.accessDate = accessDate;
		this.accessInTime = accessInTime;
		this.accessOutTime = accessOutTime;
		this.recordsCount = recordsCount;
		this.description = description;
		this.status = status;
	}

	@Column(name = "session_id", length = 32)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "login_id")
	public Integer getLoginId() {
		return this.loginId;
	}

	public void setLoginId(Integer loginId) {
		this.loginId = loginId;
	}

	@Column(name = "primary_id")
	public Integer getPrimaryId() {
		return this.primaryId;
	}

	public void setPrimaryId(Integer primaryId) {
		this.primaryId = primaryId;
	}

	@Column(name = "activity_id")
	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	@Column(name = "ip_address")
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "access_date", length = 10)
	public Date getAccessDate() {
		return this.accessDate;
	}

	public void setAccessDate(Date accessDate) {
		this.accessDate = accessDate;
	}

	@Column(name = "access_in_time", length = 45)
	public String getAccessInTime() {
		return this.accessInTime;
	}

	public void setAccessInTime(String accessInTime) {
		this.accessInTime = accessInTime;
	}

	@Column(name = "access_out_time", length = 45)
	public String getAccessOutTime() {
		return this.accessOutTime;
	}

	public void setAccessOutTime(String accessOutTime) {
		this.accessOutTime = accessOutTime;
	}

	@Column(name="records_count")
	public Integer getRecordsCount() {
		return recordsCount;
	}

	public void setRecordsCount(Integer recordsCount) {
		this.recordsCount = recordsCount;
	}

	@Column(name = "description", length = 60)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActivityLogsId))
			return false;
		ActivityLogsId castOther = (ActivityLogsId) other;

		return ((this.getSessionId() == castOther.getSessionId()) || (this
				.getSessionId() != null && castOther.getSessionId() != null && this
				.getSessionId().equals(castOther.getSessionId())))
				&& ((this.getLoginId() == castOther.getLoginId()) || (this
						.getLoginId() != null && castOther.getLoginId() != null && this
						.getLoginId().equals(castOther.getLoginId())))
				&& ((this.getPrimaryId() == castOther.getPrimaryId()) || (this
						.getPrimaryId() != null
						&& castOther.getPrimaryId() != null && this
						.getPrimaryId().equals(castOther.getPrimaryId())))
				&& ((this.getActivityId() == castOther.getActivityId()) || (this
						.getActivityId() != null
						&& castOther.getActivityId() != null && this
						.getActivityId().equals(castOther.getActivityId())))
				&& ((this.getIpAddress() == castOther.getIpAddress()) || (this
						.getIpAddress() != null
						&& castOther.getIpAddress() != null && this
						.getIpAddress().equals(castOther.getIpAddress())))
				&& ((this.getAccessDate() == castOther.getAccessDate()) || (this
						.getAccessDate() != null
						&& castOther.getAccessDate() != null && this
						.getAccessDate().equals(castOther.getAccessDate())))
				&& ((this.getAccessInTime() == castOther.getAccessInTime()) || (this
						.getAccessInTime() != null
						&& castOther.getAccessInTime() != null && this
						.getAccessInTime().equals(castOther.getAccessInTime())))
				&& ((this.getAccessOutTime() == castOther.getAccessOutTime()) || (this
						.getAccessOutTime() != null
						&& castOther.getAccessOutTime() != null && this
						.getAccessOutTime()
						.equals(castOther.getAccessOutTime())))
				&& ((this.getRecordsCount() == castOther.getRecordsCount()) || (this
						.getRecordsCount() != null
						&& castOther.getRecordsCount() != null && this
						.getRecordsCount().equals(castOther.getRecordsCount())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSessionId() == null ? 0 : this.getSessionId().hashCode());
		result = 37 * result
				+ (getLoginId() == null ? 0 : this.getLoginId().hashCode());
		result = 37 * result
				+ (getPrimaryId() == null ? 0 : this.getPrimaryId().hashCode());
		result = 37
				* result
				+ (getActivityId() == null ? 0 : this.getActivityId()
						.hashCode());
		result = 37 * result
				+ (getIpAddress() == null ? 0 : this.getIpAddress().hashCode());
		result = 37
				* result
				+ (getAccessDate() == null ? 0 : this.getAccessDate()
						.hashCode());
		result = 37
				* result
				+ (getAccessInTime() == null ? 0 : this.getAccessInTime()
						.hashCode());
		result = 37
				* result
				+ (getAccessOutTime() == null ? 0 : this.getAccessOutTime()
						.hashCode());
		result = 37
					* result
					+ (getRecordsCount() == null ? 0 : this.getRecordsCount()
							.hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
