package com.deemsys.project.entity;

// Generated Mar 16, 2016 12:32:39 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Appointments generated by hbm2java
 */
@Entity
@Table(name = "appointments" , catalog = "injuryreportsdb")
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE,region="appointments")
public class Appointments implements java.io.Serializable {

	private Long appointmentId;
	private CallLog callLog;
	private Clinic clinic;
	private Date scheduledDate;
	private String scheduledDateTime;
	private String notes;
	private Integer status;
	private Integer doctorId;
	
	public Appointments() {
	}

	public Appointments(long appointmentId) {
		this.appointmentId = appointmentId;
	}

	public Appointments(CallLog callLog,
			Date scheduledDate, String scheduledDateTime,String notes, Integer status,Clinic clinic,Integer doctorId) {
		this.callLog = callLog;
		this.scheduledDate = scheduledDate;
		this.scheduledDateTime=scheduledDateTime;
		this.notes = notes;
		this.status = status;
		this.clinic=clinic;
		this.doctorId=doctorId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "appointment_id", unique = true, nullable = false)
	public Long getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(Long appointmentId) {
		this.appointmentId = appointmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "call_log_id")
	public CallLog getCallLog() {
		return this.callLog;
	}

	public void setCallLog(CallLog callLog) {
		this.callLog = callLog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clinic_id")
	public Clinic getClinic() {
		return clinic;
	}

	public void setClinic(Clinic clinic) {
		this.clinic = clinic;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "scheduled_date",length = 10)
	public Date getScheduledDate() {
		return this.scheduledDate;
	}

	public void setScheduledDate(Date scheduledDate) {
		this.scheduledDate = scheduledDate;
	}
	
	@Column(name = "scheduled_date_time")
	public String getScheduledDateTime() {
		return scheduledDateTime;
	}

	public void setScheduledDateTime(String scheduledDateTime) {
		this.scheduledDateTime = scheduledDateTime;
	}

	@Column(name = "notes", length = 300)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "doctor_id")
	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}
	
	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	
}
