package com.deemsys.project.entity;

// Generated 4 Jan, 2018 2:04:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BlockedIp generated by hbm2java
 */
@Entity
@Table(name = "blocked_ip", catalog = "injuryreportsdb")
public class BlockedIp implements java.io.Serializable {

	private Integer id;
	private String ipAddress;
	private Integer status;

	public BlockedIp() {
	}

	public BlockedIp(String ipAddress, Integer status) {
		this.ipAddress = ipAddress;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ip_address", length = 45)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
