package com.deemsys.project.entity;

// Generated 19 Aug, 2017 10:03:05 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CrashReportError generated by hbm2java
 */
@Entity
@Table(name = "crash_report_error", catalog = "injuryreportsdb")
public class CrashReportError implements java.io.Serializable {

	private Integer crashReportErrorId;
	private String description;
	private Integer status;
	private Set<CrashReport> crashReports = new HashSet<CrashReport>(0);

	public CrashReportError() {
	}

	public CrashReportError(String description, Integer status,
			Set<CrashReport> crashReports) {
		this.description = description;
		this.status = status;
		this.crashReports = crashReports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "crash_report_error_id", unique = true, nullable = false)
	public Integer getCrashReportErrorId() {
		return this.crashReportErrorId;
	}

	public void setCrashReportErrorId(Integer crashReportErrorId) {
		this.crashReportErrorId = crashReportErrorId;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crashReportError")
	public Set<CrashReport> getCrashReports() {
		return this.crashReports;
	}

	public void setCrashReports(Set<CrashReport> crashReports) {
		this.crashReports = crashReports;
	}

}
