package com.deemsys.project.entity;

// Generated 19 Aug, 2017 10:03:05 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DirectReportLawyerAdminMapId generated by hbm2java
 */
@Embeddable
public class DirectReportLawyerAdminMapId implements java.io.Serializable {

	private String crashId;
	private int lawyerAdminId;

	public DirectReportLawyerAdminMapId() {
	}

	public DirectReportLawyerAdminMapId(String crashId, int lawyerAdminId) {
		this.crashId = crashId;
		this.lawyerAdminId = lawyerAdminId;
	}

	@Column(name = "crash_id", nullable = false, length = 45)
	public String getCrashId() {
		return this.crashId;
	}

	public void setCrashId(String crashId) {
		this.crashId = crashId;
	}

	@Column(name = "lawyer_admin_id", nullable = false)
	public int getLawyerAdminId() {
		return this.lawyerAdminId;
	}

	public void setLawyerAdminId(int lawyerAdminId) {
		this.lawyerAdminId = lawyerAdminId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DirectReportLawyerAdminMapId))
			return false;
		DirectReportLawyerAdminMapId castOther = (DirectReportLawyerAdminMapId) other;

		return ((this.getCrashId() == castOther.getCrashId()) || (this
				.getCrashId() != null && castOther.getCrashId() != null && this
				.getCrashId().equals(castOther.getCrashId())))
				&& (this.getLawyerAdminId() == castOther.getLawyerAdminId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCrashId() == null ? 0 : this.getCrashId().hashCode());
		result = 37 * result + this.getLawyerAdminId();
		return result;
	}

}
