package com.deemsys.project.entity;

// Generated 19 Aug, 2017 10:03:05 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DirectReportCallerAdminMapId generated by hbm2java
 */
@Embeddable
public class DirectReportCallerAdminMapId implements java.io.Serializable {

	private String crashId;
	private int callerAdminId;

	public DirectReportCallerAdminMapId() {
	}

	public DirectReportCallerAdminMapId(String crashId, int callerAdminId) {
		this.crashId = crashId;
		this.callerAdminId = callerAdminId;
	}

	@Column(name = "crash_id", nullable = false, length = 45)
	public String getCrashId() {
		return this.crashId;
	}

	public void setCrashId(String crashId) {
		this.crashId = crashId;
	}

	@Column(name = "caller_admin_id", nullable = false)
	public int getCallerAdminId() {
		return this.callerAdminId;
	}

	public void setCallerAdminId(int callerAdminId) {
		this.callerAdminId = callerAdminId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DirectReportCallerAdminMapId))
			return false;
		DirectReportCallerAdminMapId castOther = (DirectReportCallerAdminMapId) other;

		return ((this.getCrashId() == castOther.getCrashId()) || (this
				.getCrashId() != null && castOther.getCrashId() != null && this
				.getCrashId().equals(castOther.getCrashId())))
				&& (this.getCallerAdminId() == castOther.getCallerAdminId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCrashId() == null ? 0 : this.getCrashId().hashCode());
		result = 37 * result + this.getCallerAdminId();
		return result;
	}

}
