package com.deemsys.project.entity;

// Generated 31 Jan, 2018 6:26:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IpAccessListId generated by hbm2java
 */
@Embeddable
public class IpAccessListId implements java.io.Serializable {

	private String ipAddress;
	private int primaryLoginId;

	public IpAccessListId() {
	}

	public IpAccessListId(String ipAddress, int primaryLoginId) {
		this.ipAddress = ipAddress;
		this.primaryLoginId = primaryLoginId;
	}

	@Column(name = "ip_address", nullable = false, length = 45)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "primary_login_id", nullable = false)
	public int getPrimaryLoginId() {
		return this.primaryLoginId;
	}

	public void setPrimaryLoginId(int primaryLoginId) {
		this.primaryLoginId = primaryLoginId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IpAccessListId))
			return false;
		IpAccessListId castOther = (IpAccessListId) other;

		return ((this.getIpAddress() == castOther.getIpAddress()) || (this
				.getIpAddress() != null && castOther.getIpAddress() != null && this
				.getIpAddress().equals(castOther.getIpAddress())))
				&& (this.getPrimaryLoginId() == castOther.getPrimaryLoginId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIpAddress() == null ? 0 : this.getIpAddress().hashCode());
		result = 37 * result + this.getPrimaryLoginId();
		return result;
	}

}
