package com.deemsys.project.entity;

// Generated Feb 13, 2016 12:33:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LawyerCountyMapping generated by hbm2java
 */
@Entity
@Table(name = "lawyer_county_mapping", catalog = "injuryreportsdb")
public class LawyerCountyMapping implements java.io.Serializable {

	private Integer mappingId;
	private Lawyers lawyers;
	private County county;

	public LawyerCountyMapping() {
	}

	public LawyerCountyMapping(Lawyers lawyers, County county) {
		this.lawyers = lawyers;
		this.county = county;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mapping_id", unique = true, nullable = false)
	public Integer getMappingId() {
		return this.mappingId;
	}

	public void setMappingId(Integer mappingId) {
		this.mappingId = mappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lawyer_id")
	public Lawyers getLawyers() {
		return this.lawyers;
	}

	public void setLawyers(Lawyers lawyers) {
		this.lawyers = lawyers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "county_id")
	public County getCounty() {
		return this.county;
	}

	public void setCounty(County county) {
		this.county = county;
	}

}
