package com.deemsys.project.entity;

// Generated 19 Aug, 2017 10:03:05 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LawyerAdminCountyMapId generated by hbm2java
 */
@Embeddable
public class LawyerAdminCountyMapId implements java.io.Serializable {

	private int lawyerAdminId;
	private int countyId;

	public LawyerAdminCountyMapId() {
	}

	public LawyerAdminCountyMapId(int lawyerAdminId, int countyId) {
		this.lawyerAdminId = lawyerAdminId;
		this.countyId = countyId;
	}

	@Column(name = "lawyer_admin_id", nullable = false)
	public int getLawyerAdminId() {
		return this.lawyerAdminId;
	}

	public void setLawyerAdminId(int lawyerAdminId) {
		this.lawyerAdminId = lawyerAdminId;
	}

	@Column(name = "county_id", nullable = false)
	public int getCountyId() {
		return this.countyId;
	}

	public void setCountyId(int countyId) {
		this.countyId = countyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LawyerAdminCountyMapId))
			return false;
		LawyerAdminCountyMapId castOther = (LawyerAdminCountyMapId) other;

		return (this.getLawyerAdminId() == castOther.getLawyerAdminId())
				&& (this.getCountyId() == castOther.getCountyId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLawyerAdminId();
		result = 37 * result + this.getCountyId();
		return result;
	}

}
