package com.deemsys.project.entity;

// Generated 21 Nov, 2017 4:13:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientNearbyClinicSearchResultId generated by hbm2java
 */
@Embeddable
public class PatientNearbyClinicSearchResultId implements java.io.Serializable {

	private BigDecimal originLongitude;
	private BigDecimal originLatitude;
	private BigDecimal destinationLatitude;
	private BigDecimal destinationLongitude;

	public PatientNearbyClinicSearchResultId() {
	}

	public PatientNearbyClinicSearchResultId(BigDecimal originLongitude,
			BigDecimal originLatitude, BigDecimal destinationLatitude,
			BigDecimal destinationLongitude) {
		this.originLongitude = originLongitude;
		this.originLatitude = originLatitude;
		this.destinationLatitude = destinationLatitude;
		this.destinationLongitude = destinationLongitude;
	}

	@Column(name = "origin_longitude", nullable = false, precision = 16, scale = 11)
	public BigDecimal getOriginLongitude() {
		return this.originLongitude;
	}

	public void setOriginLongitude(BigDecimal originLongitude) {
		this.originLongitude = originLongitude;
	}

	@Column(name = "origin_latitude", nullable = false, precision = 16, scale = 11)
	public BigDecimal getOriginLatitude() {
		return this.originLatitude;
	}

	public void setOriginLatitude(BigDecimal originLatitude) {
		this.originLatitude = originLatitude;
	}

	@Column(name = "destination_latitude", nullable = false, precision = 16, scale = 11)
	public BigDecimal getDestinationLatitude() {
		return this.destinationLatitude;
	}

	public void setDestinationLatitude(BigDecimal destinationLatitude) {
		this.destinationLatitude = destinationLatitude;
	}

	@Column(name = "destination_longitude", nullable = false, precision = 16, scale = 11)
	public BigDecimal getDestinationLongitude() {
		return this.destinationLongitude;
	}

	public void setDestinationLongitude(BigDecimal destinationLongitude) {
		this.destinationLongitude = destinationLongitude;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PatientNearbyClinicSearchResultId))
			return false;
		PatientNearbyClinicSearchResultId castOther = (PatientNearbyClinicSearchResultId) other;

		return ((this.getOriginLongitude() == castOther.getOriginLongitude()) || (this
				.getOriginLongitude() != null
				&& castOther.getOriginLongitude() != null && this
				.getOriginLongitude().equals(castOther.getOriginLongitude())))
				&& ((this.getOriginLatitude() == castOther.getOriginLatitude()) || (this
						.getOriginLatitude() != null
						&& castOther.getOriginLatitude() != null && this
						.getOriginLatitude().equals(
								castOther.getOriginLatitude())))
				&& ((this.getDestinationLatitude() == castOther
						.getDestinationLatitude()) || (this
						.getDestinationLatitude() != null
						&& castOther.getDestinationLatitude() != null && this
						.getDestinationLatitude().equals(
								castOther.getDestinationLatitude())))
				&& ((this.getDestinationLongitude() == castOther
						.getDestinationLongitude()) || (this
						.getDestinationLongitude() != null
						&& castOther.getDestinationLongitude() != null && this
						.getDestinationLongitude().equals(
								castOther.getDestinationLongitude())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getOriginLongitude() == null ? 0 : this.getOriginLongitude()
						.hashCode());
		result = 37
				* result
				+ (getOriginLatitude() == null ? 0 : this.getOriginLatitude()
						.hashCode());
		result = 37
				* result
				+ (getDestinationLatitude() == null ? 0 : this
						.getDestinationLatitude().hashCode());
		result = 37
				* result
				+ (getDestinationLongitude() == null ? 0 : this
						.getDestinationLongitude().hashCode());
		return result;
	}

}
