package com.deemsys.project.entity;

// Generated 19 Aug, 2017 10:03:05 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PoliceAgency generated by hbm2java
 */
@Entity
@Table(name = "police_agency", catalog = "injuryreportsdb")
public class PoliceAgency implements java.io.Serializable {

	private int mapId;
	private County county;
	private Integer agencyId;
	private String name;
	private Integer schedulerType;
	private Integer status;
	private Date lastUpdatedDate;
	private Integer reportStatus;
	private String agencyUrl;
	private Integer reportParsingType;
	private Set<CrashReport> crashReports = new HashSet<CrashReport>(0);

	public PoliceAgency() {
	}

	public PoliceAgency(int mapId) {
		this.mapId = mapId;
	}

	public PoliceAgency(int mapId, County county, Integer agencyId,
			String name, Integer schedulerType, Integer status,
			Date lastUpdatedDate, Integer reportStatus, String agencyUrl,Integer reportParsingType,
			Set<CrashReport> crashReports) {
		super();
		this.mapId = mapId;
		this.county = county;
		this.agencyId = agencyId;
		this.name = name;
		this.schedulerType = schedulerType;
		this.status = status;
		this.lastUpdatedDate = lastUpdatedDate;
		this.reportStatus = reportStatus;
		this.agencyUrl = agencyUrl;
		this.reportParsingType=reportParsingType;
		this.crashReports = crashReports;
	}

	@Id
	@Column(name = "map_id", unique = true, nullable = false)
	public int getMapId() {
		return this.mapId;
	}

	public void setMapId(int mapId) {
		this.mapId = mapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "county")
	public County getCounty() {
		return this.county;
	}

	public void setCounty(County county) {
		this.county = county;
	}

	@Column(name = "agency_id")
	public Integer getAgencyId() {
		return this.agencyId;
	}

	public void setAgencyId(Integer agencyId) {
		this.agencyId = agencyId;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "scheduler_type")
	public Integer getSchedulerType() {
		return this.schedulerType;
	}

	public void setSchedulerType(Integer schedulerType) {
		this.schedulerType = schedulerType;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name="last_updated_date", length=10)
	public Date getLastUpdatedDate() {
		return lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name="report_status")
	public Integer getReportStatus() {
		return reportStatus;
	}

	public void setReportStatus(Integer reportStatus) {
		this.reportStatus = reportStatus;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policeAgency")
	public Set<CrashReport> getCrashReports() {
		return this.crashReports;
	}

	public void setCrashReports(Set<CrashReport> crashReports) {
		this.crashReports = crashReports;
	}
	
    @Column(name="agency_url")
	public String getAgencyUrl() {
		return agencyUrl;
	}

	public void setAgencyUrl(String agencyUrl) {
		this.agencyUrl = agencyUrl;
	}
	
	@Column(name="report_parsing_type")
	public Integer getReportParsingType() {
		return reportParsingType;
	}

	public void setReportParsingType(Integer reportParsingType) {
		this.reportParsingType = reportParsingType;
	}
}
