package com.deemsys.project.entity;

// Generated 19 Aug, 2017 10:03:05 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RatingReviews generated by hbm2java
 */
@Entity
@Table(name = "rating_reviews", catalog = "injuryreportsdb")
public class RatingReviews implements java.io.Serializable {

	private Integer ratingReviewId;
	private Users users;
	private Integer ratingQ1;
	private Integer ratingQ2;
	private Integer ratingQ3;
	private Integer ratingQ4;
	private Integer ratingQ5;
	private String reviewQ1;
	private String reviewQ2;
	private String reviewQ3;
	private String reviewQ4;
	private BigDecimal overallRating;
	private Date reviewDateTime;
	private Integer status;

	public RatingReviews() {
	}

	public RatingReviews(Users users) {
		this.users = users;
	}

	public RatingReviews(Users users, Integer ratingQ1, Integer ratingQ2,
			Integer ratingQ3, Integer ratingQ4, Integer ratingQ5,
			String reviewQ1, String reviewQ2, String reviewQ3, String reviewQ4,
			BigDecimal overallRating, Date reviewDateTime, Integer status) {
		this.users = users;
		this.ratingQ1 = ratingQ1;
		this.ratingQ2 = ratingQ2;
		this.ratingQ3 = ratingQ3;
		this.ratingQ4 = ratingQ4;
		this.ratingQ5 = ratingQ5;
		this.reviewQ1 = reviewQ1;
		this.reviewQ2 = reviewQ2;
		this.reviewQ3 = reviewQ3;
		this.reviewQ4 = reviewQ4;
		this.overallRating = overallRating;
		this.reviewDateTime = reviewDateTime;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rating_review_id", unique = true, nullable = false)
	public Integer getRatingReviewId() {
		return this.ratingReviewId;
	}

	public void setRatingReviewId(Integer ratingReviewId) {
		this.ratingReviewId = ratingReviewId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "rating_q1")
	public Integer getRatingQ1() {
		return this.ratingQ1;
	}

	public void setRatingQ1(Integer ratingQ1) {
		this.ratingQ1 = ratingQ1;
	}

	@Column(name = "rating_q2")
	public Integer getRatingQ2() {
		return this.ratingQ2;
	}

	public void setRatingQ2(Integer ratingQ2) {
		this.ratingQ2 = ratingQ2;
	}

	@Column(name = "rating_q3")
	public Integer getRatingQ3() {
		return this.ratingQ3;
	}

	public void setRatingQ3(Integer ratingQ3) {
		this.ratingQ3 = ratingQ3;
	}

	@Column(name = "rating_q4")
	public Integer getRatingQ4() {
		return this.ratingQ4;
	}

	public void setRatingQ4(Integer ratingQ4) {
		this.ratingQ4 = ratingQ4;
	}

	@Column(name = "rating_q5")
	public Integer getRatingQ5() {
		return this.ratingQ5;
	}

	public void setRatingQ5(Integer ratingQ5) {
		this.ratingQ5 = ratingQ5;
	}

	@Column(name = "review_q1", length = 250)
	public String getReviewQ1() {
		return this.reviewQ1;
	}

	public void setReviewQ1(String reviewQ1) {
		this.reviewQ1 = reviewQ1;
	}

	@Column(name = "review_q2", length = 250)
	public String getReviewQ2() {
		return this.reviewQ2;
	}

	public void setReviewQ2(String reviewQ2) {
		this.reviewQ2 = reviewQ2;
	}

	@Column(name = "review_q3", length = 250)
	public String getReviewQ3() {
		return this.reviewQ3;
	}

	public void setReviewQ3(String reviewQ3) {
		this.reviewQ3 = reviewQ3;
	}

	@Column(name = "review_q4", length = 250)
	public String getReviewQ4() {
		return this.reviewQ4;
	}

	public void setReviewQ4(String reviewQ4) {
		this.reviewQ4 = reviewQ4;
	}

	@Column(name = "overall_rating", precision = 4)
	public BigDecimal getOverallRating() {
		return this.overallRating;
	}

	public void setOverallRating(BigDecimal overallRating) {
		this.overallRating = overallRating;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "review_date_time", length = 19)
	public Date getReviewDateTime() {
		return this.reviewDateTime;
	}

	public void setReviewDateTime(Date reviewDateTime) {
		this.reviewDateTime = reviewDateTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
