package com.deemsys.project.entity;

// Generated 19 Aug, 2017 10:03:05 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserLookupPreferences generated by hbm2java
 */
@Entity
@Table(name = "user_lookup_preferences", catalog = "injuryreportsdb")
public class UserLookupPreferences implements java.io.Serializable {

	private UserLookupPreferencesId id;
	private Users users;

	public UserLookupPreferences() {
	}

	public UserLookupPreferences(UserLookupPreferencesId id, Users users) {
		this.id = id;
		this.users = users;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "type")),
			@AttributeOverride(name = "countyId", column = @Column(name = "county_id")),
			@AttributeOverride(name = "preferedId", column = @Column(name = "prefered_id")),
			@AttributeOverride(name = "status", column = @Column(name = "status")) })
	public UserLookupPreferencesId getId() {
		return this.id;
	}

	public void setId(UserLookupPreferencesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
